spring:
  datasource:
    url: jdbc:sqlserver://lms19.database.windows.net:1433;database=course_management_db;
    username: CloudSA96eccfc5@lms19
    password: Nozom@2020
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  application:
    name: courseManagementService
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
